driver:
  name: dokken
  privileged: true
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

platforms:
- name: amazonlinux
  driver:
    image: dokken/amazonlinux

- name: amazonlinux-2
  driver:
    image: dokken/amazonlinux-2

- name: debian-7
  driver:
    image: dokken/debian-7

- name: debian-8
  driver:
    image: dokken/debian-8

- name: debian-9
  driver:
    image: dokken/debian-9

- name: centos-6
  driver:
    image: dokken/centos-6

- name: centos-7
  driver:
    image: dokken/centos-7

- name: fedora-latest
  driver:
    image: dokken/fedora-latest

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04

- name: ubuntu-18.04
  driver:
    image: dokken/ubuntu-18.04